#image:
#  file: .gitpod.Dockerfile

tasks:
  - init: |
      sbt setup
  - command: |      
      cd sparkler-core && sbt assembly package
ports:
  - port: 8080
    visibility: public
    onOpen: open-browser  
