version: '2'
services:
  single-server-int:
    networks:
      - sparkler
    image: arangodb:3.4.6
    ports:
      - 8529:8529
    environment:
        - ARANGO_NO_AUTH=1
    volumes:
      - db:/var/lib/arangodb3
  sce-solr:
    image: uscdatascience/sparkler-solr:latest
    networks:
      - sparkler
    ports:
     - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/mycores
    command: ['/data/solr/bin/solr','start','-f']

  sce-splash:
    image: scrapinghub/splash
    networks:
      - sparkler
    ports:
      - 8050:8050

  sce-ui:
    image: uscdatascience/sparkler-ui:latest
    networks:
      - sparkler
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - models:/models
volumes:
 data:
 db:
 models:

networks:
  sparkler:
    external:
      name: sparkler
