#!/usr/bin/env bash

set -ex

## TODO implement custom job it
JOBID=`action-get jobid`

CRAWLDB=`config-get crawldb-uri`

java -jar /opt/sparkler/sparkler-app-0.1-SNAPSHOT.jar inject -sf /opt/sparkler/seed.txt -cdb "$CRAWLDB"






