apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "single-server"
spec:
  mode: Single
---
kind: Service
apiVersion: v1
metadata:
  name: arangodb-cluster-exposed
spec:
  selector:
    arango_deployment: arangodb-cluster
    role: coordinator
  type: NodePort
  ports:
    - protocol: TCP
      port: 8529
      targetPort: 8529
      nodePort: 30529
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sce-solr
  labels:
    app: sce-solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sce-solr
  template:
    metadata:
      labels:
        app: sce-solr
    spec:
      containers:
        - name: sce-solr
          image: registry.gitlab.com/sparkler-crawl-environment/sparkler/solr:memex-dd
          command: ['/data/solr/bin/solr','start','-f']
          ports:
            - name: http
              containerPort: 8983
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sce-firefox
  labels:
    app: sce-firefox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sce-firefox
  template:
    metadata:
      labels:
        app: sce-firefox
    spec:
      containers:
        - name: sce-firefox
          image: selenium/standalone-firefox-debug
          ports:
            - name: http
              containerPort: 4444
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sce-api
  labels:
    app: sce-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sce-api
  template:
    metadata:
      labels:
        app: sce-api
    spec:
      containers:
        - name: sce-api
          image: registry.gitlab.com/sparkler-crawl-environment/memex-dd:memex-dd
          env:
            - name: WEBDRIVER_URL
              value: "http://sce-firefox:4444/wd/hub"
          ports:
            - name: http
              containerPort: 5000
          imagePullPolicy: Always
      imagePullSecrets:
        - name: gitlab-registry
---
apiVersion: v1
kind: Service
metadata:
  name: sce-api
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: sce-api
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: sce-firefox
spec:
  ports:
    - name: http
      port: 4444
      protocol: TCP
      targetPort: 4444
  selector:
    app: sce-firefox
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: sce-solr
spec:
  ports:
    - name: http
      port: 8983
      protocol: TCP
      targetPort: 8983
  selector:
    app: sce-solr
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sce-ui
  labels:
    app: sce-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sce-ui
  template:
    metadata:
      labels:
        app: sce-ui
    spec:
      containers:
      - name: sce-ui
        image: registry.gitlab.com/sparkler-crawl-environment/sce-ui:latest
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
      - name: gitlab-registry
---
apiVersion: v1
kind: Service
metadata:  
    name: sce-ui
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sce-ui
  type: NodePort
